create table users (
    id uuid primary key default gen_random_uuid(),
    last_name text not null,
    first_name text not null,
    patronymic text default null,
    email varchar(320) not null unique,
    phone varchar(12) not null unique,
    birth date not null,
    password_hash text not null,

    created_at timestamptz not null default now(),
    modified_at timestamptz default null,
    is_deleted boolean not null default false,

    check (email ~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'),
    check (phone ~* '^\+7[0-9]{10}$')
);

create table revoked_tokens (
    id int generated by default as identity primary key,
    user_id uuid not null references users(id) on delete cascade,
    token text not null,
    revoked_at timestamptz not null default now()
);

create table categories (
    id int generated by default as identity primary key,
    category_name text not null unique,
    parent_category_id int default null references categories(id) on set null,

    check (parent_category_id != id)
);

create table products (
    id int generated by default as identity primary key,
    category_id int not null references categories(id) on delete cascade
);

create table products_variations (
    id uuid primary key default gen_random_uuid(),
    product_id int not null references products(id) on delete cascade,
    variant_name text not null,
    price_rub int not null,

    created_at timestamptz not null default now(),
    modified_at timestamptz default null,
    is_deleted boolean not null default false,

    check (price_rub > 0)
);

create table characteristics (
    id int generated by default as identity primary key,
    c_name text not null,
    units text default null,
    
    constraint uq_c_name_units unique (c_name, units)
);

create table products_variations_characteristics (
    id uuid primary key default gen_random_uuid(),
    variant_id uuid not null references products_variations(id) on delete cascade,
    c_id int not null references characteristics(id) on delete cascade,
    c_value text not null,

    constraint uq_variant_id_c_id unique (variant_id, c_id)
);

-- субъекты РФ
create table subjects (
    id int generated by default as identity primary key,
    subject_name text not null unique
);

-- районы
create table districts (
    id int generated by default as identity primary key,
    district_name text not null,
    subject_id int not null references subjects(id) on delete cascade,

    constraint uq_district_name_subject_id unique (district_name, subject_id)
);

-- населённые пункты - привязаны к району или субъекту РФ,
-- но не к обоим одновременно (район в адресе может быть пропущен)
create table settlements (
    id int generated by default as identity primary key,
    settlement_name text not null,
    subject_id int not null references subjects(id) on delete cascade,
    district_id int references districts(id) on delete cascade,

    constraint uq_settlement_name_subject_id_district_id
    unique (settlement_name, subject_id, district_id)
);

-- микрорайоны, кварталы
create table locality_elements (
    id int generated by default as identity primary key,
    locality_element_name text not null,
    settlement_id int not null references settlements(id) on delete cascade,

    constraint uq_locality_element_name_settlement_id
    unique (locality_element_name, settlement_id)
);

-- элемент улично-дорожной сети (улица, проспект и тп) - привязаны к
-- микрорайону или городу, но не к обоим одновременно (микрорайон может быть пропущен)
create table road_network_elements (
    id int generated by default as identity primary key,
    road_network_element_name text not null,
    settlement_id int not null references settlements(id) on delete cascade,
    locality_element_id int references locality_elements(id) on delete cascade,

    constraint uq_road_network_element_name_settlement_id_locality_element_id
    unique (road_network_element_name, settlement_id, locality_element_id)
);

-- идентификация объекта адресации (дом 7/1А)
create table addressing_objects (
    id int generated by default as identity primary key,
    house_designation text not null,
    road_network_element_id int not null
    references road_network_elements(id) on delete cascade,

    constraint uq_house_designation_road_network_element_id
    unique (house_designation, road_network_element_id)
);

create table delivery_addresses (
    id int generated by default as identity primary key,
    user_id uuid not null references users(id) on delete cascade,
    addr_object_id int not null references addressing_objects(id) on delete cascade,
    flat int default null,

    constraint uq_user_id_addr_object_id_flat unique (user_id, addr_object_id, flat)
);

create table warehouses (
    id int generated by default as identity primary key,
    addr_object_id int not null references addressing_objects(id) on delete cascade
);

create table warehouses_products_variations (
    id int generated by default as identity primary key,
    warehouse_id int not null references warehouses(id) on delete cascade,
    product_variant_id uuid not null
    references products_variations(id) on delete cascade,
    amount int not null default 0,

    constraint uq_warehouse_id_product_variant_id
    unique (warehouse_id, product_variant_id),

    check (amount >= 0)
);

create table users_backets (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references users(id) on delete cascade,
    product_variant_id uuid not null references products_variations(id) on delete cascade,
    amount int not null,
    
    created_at timestamptz not null default now(),

    constraint uq_user_id_product_variant_id unique (user_id, product_variant_id),

    check (amount > 0)
);

create table products_variations_likes (
    id int generated by default as identity primary key,
    user_id uuid not null references users(id) on delete cascade,
    product_variant_id uuid not null references products_variations(id) on delete cascade,
    
    created_at timestamptz not null default now(),

    constraint uq_user_id_product_variant_id unique (user_id, product_variant_id)
);

create table orders (
    id int generated by default as identity primary key,
    user_id uuid not null references users(id) on delete cascade,

    created_at timestamptz not null default now()
);

create table orders_products_variations (
    id uuid primary key default gen_random_uuid(),
    order_id int not null references orders(id) on delete cascade,
    product_variant_id uuid not null references products_variations(id) on delete cascade,
    amount int not null,
    price_rub int not null,
    warehouse_id int not null references warehouses(id) on delete cascade,
    estimated_delivery_date date not null,
    
    constraint uq_order_id_product_variant_id_warehouse_id unique (order_id, product_variant_id, warehouse_id),

    check (amount > 0),
    check (price_rub > 0)
);

create table delivery_statuses (
    id int generated by default as identity primary key,
    status_name text not null unique
);

-- состояние могут логически изменяться только сверху вниз, при этом статус "Отменён" может появится после любого из предыдущих статусов;
-- если предыдущий статус является "Отправлен",
-- то в случае отмены после стутса "Отменён" идёт статус "Возвращается на склад", иначе статус "Возвращается на склад" не используется
insert into delivery_statuses (status_name) values
    ('Оформлен, готовится к сборке'),
    ('Собирается'),
    ('Собран, готовится к отправке'),
    ('Отправлен'),
    ('Получен'),
    ('Отменён'),
    ('Возвращается на склад'),
    ('Вернулся на склад');

-- если о какой либо позиции заказа нет информации в этой таблице, то считать статус "В процессе оформления"
create table orders_history (
    id int generated by default as identity primary key,
    order_product_variation_id uuid not null references orders_products_variations(id) on delete cascade,
    delivery_status_id int not null references delivery_statuses(id) on delete cascade,

    created_at timestamptz not null default now()
);

create table product_rejections (
    id int generated by default as identity primary key,
    order_products_id uuid not null references orders_products_variations(id) on delete cascade,
    amount int not null,
    reason text not null,

    check (amount > 0)
);

create table supplies (
    id uuid primary key default gen_random_uuid(),
    product_variant_id uuid not null references products_variations(id) on delete cascade,
    amount int not null,
    warehouse_id int not null references warehouses(id) on delete cascade,

    created_at timestamptz not null default now(),

    check (amount > 0)
);