create table users (
    id uuid primary key default gen_random_uuid(),
    last_name text not null,
    first_name text not null,
    patronymic text default null,
    email varchar(320) not null unique,
    phone varchar(12) not null unique,
    birth date not null,

    created_at timestamptz not null default now(),
    modified_at timestamptz default null,
    is_deleted boolean not null default false,

    check (email ~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$)'),
    check (phone ~* '^\+7[0-9]{10}$')
);

create table categories (
    id int generated by default as identity primary key,
    category_name text not null unique,
    parent_category_id int default null references categories(id) on set null,

    check (parent_category_id != id)
);

create table products (
    id int generated by default as identity primary key,
    category_id int not null references categories(id) on delete cascade
);

create table products_variations (
    id uuid primary key default gen_random_uuid(),
    product_id int not null references products(id) on delete cascade,
    variant_name text not null,
    price_rub int not null,

    created_at timestamptz not null default now(),
    modified_at timestamptz default null,
    is_deleted boolean not null default false,

    check (price_rub > 0)
);

create table characteristics (
    id int generated by default as identity primary key,
    c_name text not null,
    units text default null,
    
    constraint uq_c_name_units unique (c_name, units)
);

create table products_variations_characteristics (
    id uuid primary key default gen_random_uuid(),
    variant_id uuid not null references products_variations(id) on delete cascade,
    c_id int not null references characteristics(id) on delete cascade,
    c_value text not null,

    constraint uq_variant_id_c_id unique (variant_id, c_id)
);